### ISSUE TITLE
Grafana will not authenticate with the OCI Data Source

### ISSUE THREAD

**Issue by danxtrate** [oracle/oci-grafana-plugin#1]
hello, 

I have tried to do the installation in a CentOS environment running in Vagrant. 
I have followed the guide to the letter, but whenever I try to connect the datasource to my tenancy I get the following message: 

**reject: too many failed attempts: [object Object]**

I have tried the following:
 - Double checked all the credentials and OCID's, the tenancy OCID I'm using in Grafana is the same as in the ~/.oci/config file for oci-cli
 - the user I have created for grafana has the same OCID in the OCI console as in the config file for OCI cli and I can run oci-cli commands no problem
 - I have made the grafana user full OCI admin

Still I get the same error. Any ideas what to troubleshoot next?

**Comment by faiq** [comment]
Hey @danxtrate thanks for checking reporting this issue. 

The first thing I would try is setting Grafana's log level to debug you can do this by setting this environment variable like so `export GF_LOG_LEVEL=debug` and restarting the Grafana service.

Let me know what the logs look like and we can solve it from there.

**Comment by danxtrate** [comment]
This is the log output:

> t=2019-03-04T07:44:06+0000 lvl=info msg="Shutdown started" logger=server reason="System signal: terminated"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped CleanUpService" logger=server
> reason="context canceled"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped UserAuthTokenService" logger=server reason="context canceled"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped Stream Manager"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped ProvisioningService" logger=server reason="context canceled"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped NotificationService" logger=server reason="context canceled"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped RenderingService" logger=server reason=nil
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped InternalMetricsService" logger=server reason="context canceled"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped TracingService" logger=server
> reason=nil
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped AlertingService" logger=server reason="context canceled"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped PluginManager" logger=server reason="context canceled"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Stopped HTTPServer" logger=server reason=nil
> t=2019-03-04T07:44:06+0000 lvl=eror msg="Server shutdown" logger=server reason="System signal: terminated"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Starting Grafana" logger=server version=6.0.0 commit=34a9a62 branch=HEAD compiled=2019-02-25T14:47:26+0000
> t=2019-03-04T07:44:06+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
> t=2019-03-04T07:44:06+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
> t=2019-03-04T07:44:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
> t=2019-03-04T07:44:06+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
> t=2019-03-04T07:44:06+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
> t=2019-03-04T07:44:06+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
> t=2019-03-04T07:44:06+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
> t=2019-03-04T07:44:06+0000 lvl=info msg="App mode production" logger=settings
> t=2019-03-04T07:44:06+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=6057
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing HTTPServer" logger=servert=2019-03-04T07:44:06+0000 lvl=info msg="Initializing SqlStore" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
> t=2019-03-04T07:44:06+0000 lvl=info msg="Starting DB migration" logger=migratort=2019-03-04T07:44:06+0000 lvl=info msg="Initializing InternalMetricsService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing SearchService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing PluginManager" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Starting plugin search" logger=pluginst=2019-03-04T07:44:06+0000 lvl=info msg="Registering plugin" logger=plugins name="Oracle Cloud Infrastructure"
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing RenderingService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing AlertingService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing DatasourceCacheService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing HooksService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing LoginService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing QuotaService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing ServerLockService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing UserAuthTokenService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing CleanUpService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing NotificationService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing ProvisioningService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing TracingService" logger=server
> t=2019-03-04T07:44:06+0000 lvl=info msg="Initializing Stream Manager"
> t=2019-03-04T07:44:06+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
> t=2019-03-04T07:45:40+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:40+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=3 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:40+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:40+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=2 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:41+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:41+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:42+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:42+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:42+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:42+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:44+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:44+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:45+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:45+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=2 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:45:47+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:45:47+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:46:25+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:25+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=2 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:46:25+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:25+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=2 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:46:26+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:26+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:46:26+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:26+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:46:27+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:27+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:46:28+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:28+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=2 size=34 referer=http://localhost:3000/datasources/edit/6/
> t=2019-03-04T07:46:29+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with
> client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:29+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhionProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:30+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=2 size=34 referer=http://localhost:3000/datasources/edit/6/t=2019-03-04T07:46:30+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with client(common.composingConfigurationProvider) {\n
> Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client,
> bad configuration: did not find a proper configuration for tenancy"
> t=2019-03-04T07:46:30+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=10.0.2.2 time_ms=1 size=34 referer=http://localhost:3000/datasources/edit/6/

**Comment by danxtrate** [comment]
While going through the log, realized a couple of things: 
> Configuration provided by file: /usr/share/grafana/.oci/config 
There is no such file, I have copied the ~/.oci/config file to this path, restarted the service, did not work

>  Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client,
There is no TF_VAR variable in my system, it's a fresh Centos box with no customization whatsoever. Looks like some sort of Terraform remenant, but I have not installed Terraform on this system.

**Comment by danxtrate** [comment]
Got thingg working with help from @faiq , two things that need to be done:
1. Move the ~/.oci folder to /usr/share/grafana
2. change ownership of the /usr/share/grafana/.oci folder to the "grafana" user:
`sudo chown -R grafana:grafana /usr/share/grafana/.oci`

**Comment by iamndash** [comment]
Hi Dan,

I'm exactly facing the same issue and did copy as you mentioned. The _oci_ user was able to execute all oci-cli commands but when I tried to add the datasource it gives the same error as yours. Any pointers are greatly appreciated.


_t=2022-06-15T17:44:24+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: **did not find a proper configuration for private key**"
t=2022-06-15T17:44:24+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query_

Thanks
