### ISSUE TITLE
Save & Test for Oracle Cloud Infrastructure keeps failing for a specific Tenancy

### ISSUE THREAD

**Issue by jpal-github** [oracle/oci-grafana-plugin#17]
I have reviewed all other threads but still have the issue:

[1] ~/.oci/config is verified
[2] I can run oci-cli commands for the tenancy
     (ex: oci iam compartment list -c <tenancy ocid> --all|grep name|wc -l
          gives 28)
[3] Copied over ~/.oci folder to /usr/share/grafana
[4] Updated /usr/share/grafana/.oci/config to have the correct key_file location and restarted grafana

Error is as below:
--------------------
t=2019-07-22T06:43:59+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = list metrircs failed (monitoring.ListMetricsResponse) { RawResponse={404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[111] Content-Type:[application/json] Date:[Mon, 22 Jul 2019 06:43:59 GMT] Opc-Request-Id:[837270ff8db935433c4707d2bb20274d/9002BE201021B034C376681B70A0290F/1665B3A05DBF92A40FF49863467CA9A5]] 0xc0004576a0 111 [] false false map[] 0xc0004de000 0xc0000c2580} Items=[] OpcNextPage=<nil> OpcRequestId=<nil> }\n 404: Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 404. Opc request id: 837270ff8db935433c4707d2bb20274d/9002BE201021B034C376681B70A0290F/1665B3A05DBF92A40FF49863467CA9A5"
t=2019-07-22T06:43:59+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=209.17.43.236 time_ms=100 size=34 referer=<url>

**Comment by bhushan2901** [comment]
what are the permissions and owner of " /usr/share/grafana/.oci/" directory ?

**Comment by jpal-github** [comment]
Hi the problem was resolved and was due to access issue. An IAM policy setup to access all metric in teh tenancy worked fine.
