### ISSUE TITLE
reject: too many failed attempts: [object Object]

### ISSUE THREAD

**Issue by stretchcloud** [oracle/oci-grafana-plugin#2]
I am running Grafana on my Raspberry Pi. Grafana has the appropriate binary for my ARMv7 architecture type. So I thought I can pull it off. However, the error below suggests something else.

Any idea if the Plug-in supports ARMv7? My OCI CLI is working perfectly and authenticating to my Tenancy. It's the Grafana OCI plug in which is not.

t=2019-03-05T16:18:08+0000 lvl=eror msg="Failed to init plugin." logger=plugins error="fork/exec /var/lib/grafana/plugins/oci-datasource/dist/oci-plugin_linux_arm: no such file or directory" plugin=oci-datasource
t=2019-03-05T16:18:08+0000 lvl=info msg="Initializing Stream Manager"
t=2019-03-05T16:18:08+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2019-03-05T16:18:30+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: oci-datasource"
t=2019-03-05T16:18:30+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.146 time_ms=4 size=34 referer=http://192.168.1.34:3000/datasources/edit/1/
t=2019-03-05T16:18:31+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: oci-datasource"
t=2019-03-05T16:18:31+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.146 time_ms=6 size=34 referer=http://192.168.1.34:3000/datasources/edit/1/
t=2019-03-05T16:18:32+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: oci-datasource"
t=2019-03-05T16:18:32+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.146 time_ms=6 size=34 referer=http://192.168.1.34:3000/datasources/edit/1/
t=2019-03-05T16:18:32+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: oci-datasource"
t=2019-03-05T16:18:32+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.146 time_ms=3 size=34 referer=http://192.168.1.34:3000/datasources/edit/1/
t=2019-03-05T16:18:33+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: oci-datasource"
t=2019-03-05T16:18:33+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.146 time_ms=3 size=34 referer=http://192.168.1.34:3000/datasources/edit/1/
t=2019-03-05T16:18:33+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: oci-datasource"
t=2019-03-05T16:18:33+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=192.168.1.146 time_ms=6 size=34 referer=http://192.168.1.34:3000/datasources/edit/1/
t=2019-03-05T16:18:34+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: oci-datasource"

**Comment by stretchcloud** [comment]
I have tried the resolution mentioned by the other user as well. This also did not help me.

Got this working with help from @faiq (thanks for that!), two things that need to be done:

Move the ~/.oci folder to /usr/share/grafana
change ownership of the /usr/share/grafana/.oci folder to the "grafana" user:
sudo chown -R grafana:grafana /usr/share/grafana/.oci

**Comment by mickeyboxell** [comment]
The plugin is currently not compatible with 32-bit operating systems.

**Comment by mbgch** [comment]
@stretchcloud : and change the content of the file /usr/share/grafana/.oci to point to your key location.

**Comment by mbgch** [comment]
@mickeyboxell do you know if it's compatible on an Raspberry Pi?

**Comment by mickeyboxell** [comment]
Hi @mbgch - the plugin is currently not compatible with 32-bit operating systems, so I do not believe it would work with a Raspberry Pi.
