### ISSUE TITLE
Not a valid zip file

### ISSUE THREAD

**Issue by mikwagner** [oracle/oci-grafana-plugin#25]
Hello,

I have been using the oci datasource plugin successfully for a couple of weeks now, but it stopped working.  When I try to install it, I get the following error message:

$ grafana-cli plugins install oci-datasource
installing oci-datasource @ 1.0.2
from: https://grafana.com/api/plugins/oci-datasource/versions/1.0.2/download
into: /var/lib/grafana/plugins

Error: ✗ zip: not a valid zip file

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
$

**Comment by VadimKomar** [comment]
Hi @mikwagner,
Today the latest version(1.04) of the plugin is available only with the manual installation.
Linux
https://github.com/oracle/oci-grafana-plugin/blob/master/docs/linux.md#manually-installation
MACOS
https://github.com/oracle/oci-grafana-plugin/blob/master/docs/macos.md#manually-installation

p.s. We are working on your issue, It takes time to integrate the plugin  with grafana repository.
