### ISSUE TITLE
404 error - Link to next steps 

### ISSUE THREAD

**Issue by eoinkehoe** [oracle/oci-grafana-plugin#4]
![404](https://user-images.githubusercontent.com/40172744/53894939-e2d52600-4028-11e9-8f1f-bff3b119d1b7.PNG)

Steps are successful but when adding OCI as a data source errors are received and the link provided in repo is broken. Thanks

**Comment by mickeyboxell** [comment]
Thanks for letting me know. I will update the hyperlink.
