### ISSUE TITLE
Grafana will not authenticate with the OCI Data Source given error  "Data source not found"

### ISSUE THREAD

**Issue by kapdevl** [oracle/oci-grafana-plugin#40]
hello,

I have tried to do the installation in a MAC OS environment.
I have followed the guide to configure the OCI datasource in grafana, but whenever I try to connect the datasource to my tenancy I get the following message:
Data source not found
I have tried the following:

    I checked all the credentials and OCID's, the tenancy OCID I'm using in Grafana is the same as in the ~/.oci/config file for oci-cli
Any ideas what to troubleshoot next?

**Comment by kapildevgangrade** [comment]
t=2020-02-06T11:23:03+0530 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /Users/mac/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /Users/mac/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for tenancy"
t=2020-02-06T11:23:03+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=[::1] time_ms=2 size=34 referer=http://localhost:3000/datasources/edit/19/?gettingstarted

**Comment by MGralike** [comment]
Have you checked/altered the different path in the "config" file (plus changed the rw / ownership of the file)?

**Comment by kapil-devl** [comment]
yes we checked with alternate path :
/usr/local/share/grafana/.oci/
But we facing same issue
Also give the rw permission 
can you explain the ownership??because .oci folder root access

**Comment by MGralike** [comment]
Grafana is started via "grafana" user so should be able to read the OCI related files for access.

**Comment by kapil-devl** [comment]
so i need to create a grafana user then install grafana with grafana user??

**Comment by kapdevl** [comment]
-rwxrwxrwx   1 grafana   grafana  16308140 Nov 27 04:13 oci-plugin_darwin_amd64
-rwxrwxrwx   1 grafana   grafana  16462193 Nov 27 04:34 oci-plugin_linux_amd64

**Comment by MGralike** [comment]
systemctl status grafana.server etc will give you the path to the log files. Anything useful in the log files???

**Comment by kapdevl** [comment]
Issue is resolved 
given the read write permission config and key file

**Comment by iamndash** [comment]
@kapdevl  Could you please elaborate how did it resolve? Did you give permission under /user/share/grafana or /home/oci? I'm facing the following error despite all the correct permission.

t=2022-06-15T17:39:49+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = error with client(common.composingConfigurationProvider) {\n Providers: ([]common.ConfigurationProvider) (len=3 cap=3) {\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oci/config,\n  (common.fileConfigurationProvider) Configuration provided by file: /usr/share/grafana/.oraclebmc/config,\n  (common.environmentConfigurationProvider) Configuration provided by environment variables prefixed with: TF_VAR\n }\n}\ncan not create client, bad configuration: did not find a proper configuration for private key"
