### ISSUE TITLE
Wrong list of regions in plugin

### ISSUE THREAD

**Issue by ramnathnayakpr** [oracle/oci-grafana-plugin#5]
Two issues:

1. Plugin lists non-commercial regions SEA, LFI, LUF while configuring.

2. Missing YYZ commercial region.
<img width="708" alt="Screen Shot 2019-03-31 at 19 22 02" src="https://user-images.githubusercontent.com/8271471/55293098-5715a600-53ea-11e9-86c1-b71356591ebf.png">

**Comment by mickeyboxell** [comment]
Commit https://github.com/oracle/oci-grafana-plugin/commit/de26bc660c94eb7ae9b54f0aff136d237335324c closes this issue.
