### ISSUE TITLE
I remember testing this change yesterday but now it has gone missing. plugin.tar doesn't contain this change

### ISSUE THREAD

**Issue by viralkamdar** [oracle/oci-grafana-plugin#78]
I remember testing this change yesterday but now it has gone missing. plugin.tar doesn't contain this change

_Originally posted by @viralkamdar in https://github.com/oracle/oci-grafana-plugin/issues/75#issuecomment-754560940_

**Comment by athulmurali** [comment]
I too see that Dubai is not present in src/constants.js when plugin.tar is unpacked . 

Now that I have removed the plugin.tar and re-uploaded in the same release. 

Please confirm if the issue is fixed.

**Comment by viralkamdar** [comment]
It's fixed now. Thanks
